### ISSUE TITLE
Add meaningful description to github repository

### ISSUE THREAD

**Issue by nadjaheitmann** [theforeman/hammer-cli-foreman-puppet#14]
What about something like `Adds Puppet functionality for Hammer Foreman CLI ` or `Hammer CLI Foreman plugin for Foreman Puppet ` ?

**Comment by amirfefer** [comment]
The first one is a bit more explicit, so I'd go with it :)

**Comment by nadjaheitmann** [comment]
Okay, you need to change it, I think you are the only maintainer right now ;) Or is there anybody I am not aware of?

**Comment by amirfefer** [comment]
done
